paths: {}
collections_config:
  blog:
    path: src/content/blog
    icon: event_available
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: src/pages
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    url: /[full_slug]/
    _enabled_editors:
      - visual
      - source
timezone: Etc/UTC
